# git settings
source /usr/local/git/contrib/completion/git-prompt.sh
source /usr/local/git/contrib/completion/git-completion.bash
GIT_PS1_SHOWDIRTYSTATE=true
export PS1='\[\033[34m\]\w\[\033[32m\]$(__git_ps1)\[\033[00m\]
\$ '

# alias
alias bashrc='open ~/.bashrc'
alias bashrcc='source ~/.bashrc && cd ~/dotfiles/ && git st'
alias be='bundle exec'
alias bi='bundle install --path vendor/bundle'
alias branch='git branch-empty-commit'
alias cc='compass compile'
alias cw='compass watch'
alias chmodd='stat -f %A'
alias d='git checkout develop'
alias dd='git checkout develop && git pull && git pull origin develop'
alias dayone='dayone new'
alias findfile='find . -name'
alias finddir='find . -type d -name'
alias firefox='open -a firefox'
alias google='open http://www.google.co.jp/'
alias g='git'
alias gs='git st'
alias ga='git add'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gcaa='git commit --amend --no-edit'
alias gce='git commit --allow-empty -m'
alias gd='git diff'
alias gdw='git diff | nkf -w'
alias gdd='git diff --cached'
alias gddw='git diff --cached | nkf -w'
alias gt='git'
alias j='jekyll'
alias jb='jekyll build'
alias js='jekyll serve'
alias jsw='jekyll serve --watch'
alias ls='ls -1'
alias m='git checkout master'
alias mm='git checkout master && git pull && git pull origin master'
alias mameblo='python ~/mameblo/cli/mameblo.py'
alias moji='nkf --guess'
alias mkdirr='mkdir -p'
alias nd='DEBUG=* node-dev'
alias o='open'
alias p='pinboard'
alias push='git push-origin'
alias r='rbenv'
alias reload='source ~/.bashrc'
alias rs='bundle exec rails server'
alias rspecc='bundle exec rspec spec'
alias gitpush='bundle exec rspec spec'
alias v='vim'
alias vi='vim'
alias vv='vi'
alias vu='vagrant up'
alias vh='vagrant halt'
alias wip='git commit --allow-empty -m ":construction: WIP"'
alias youtube='mpsyt'

# Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
